import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Bar, Doughnut } from 'react-chartjs-2';
import { LinearScale,CategoryScale, Chart,BarElement,ArcElement,Tooltip } from "chart.js";
import { createClient } from 'redis';

Chart.register([LinearScale, CategoryScale,BarElement, ArcElement,Tooltip])

const getReportData = redisClient => async(name) => {
  const reportKey = `report:${name}`
  const reportLabelKey = `${reportKey}:labels`
  try {
    const labelsLengthSize = await redisClient.lLen(reportLabelKey)
    const labels = (await redisClient.lRange(reportLabelKey,0, labelsLengthSize))//.map(s => s.substring(0,5))
    const datasetsKeys = await redisClient.hGetAll(`${reportKey}:datasets`)
 
    const datasets = []
    
    for (const [label, value] of Object.entries(datasetsKeys)){
    
      const size = await redisClient.lLen(value)
      const data = (await redisClient.lRange(value,0,size)).map(v => Number(v))

      console.log("data:", data)

      datasets.push({label,data}) 
    }

    return {name,labels, datasets}
  } catch (error) {
    console.error(error)
  }
}

export async function getServerSideProps(context) {

  const client = createClient();

  client.on('error', (err) => console.log('Redis Client Error', err));

  await client.connect();

  const reportList = await client.sMembers('report:list');
  console.log("reports", reportList)
  const reports = await Promise.all(reportList.map(getReportData(client)))
 
  await client.disconnect();

    return {
      props: {
        reports
      },
    };
}

export default function Home({reports}) {

  const group_and_count_agents =  (reports.filter(r => r.name === 'group_and_count_agents'))[0]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.grid}>
        <Doughnut data={{
              ...group_and_count_agents
             }}
            options={{
              interaction: {
                mode: 'point'
              },
              plugins: {
                tooltip:{
                  enabled:true
                },
                legend: {
                  display:false,
                },
                title: {
                  display: true,
                  text: "Test chart",
                  position: "top"
                }
              },
              backgroundColor: [
                'rgba(255, 99, 132, 0.7)',
                'rgba(255, 159, 64, 0.7)',
                'rgba(255, 205, 86, 0.7)',
                'rgba(89, 99, 132, 0.7)',
                'rgba(45, 18, 64, 0.7)',
                'rgba(78, 205, 86, 0.7)',
                'rgba(67, 78, 132, 0.7)',
                'rgba(123, 15, 64, 0.7)',
                'rgba(255, 20, 86, 0.7)',
                'rgba(255, 177, 86, 0.7)'
              ]
            }} />
            </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" >
            <h2>Documentation &rarr;</h2>
           
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
