import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Bar } from 'react-chartjs-2';
import { LinearScale,CategoryScale, Chart,BarElement } from "chart.js";
import { createClient } from 'redis';

Chart.register([LinearScale, CategoryScale,BarElement])

export async function getServerSideProps(context) {

const client = createClient();

client.on('error', (err) => console.log('Redis Client Error', err));

await client.connect();

await client.set('key', 'value');
const value = await client.get('key');
await client.disconnect();

  return {
    props: {
      report: {
        r1:{data:"Good stuff"}
      }
    },
  };
}

export default function Home({report}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App {report.r1.data}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <Bar data={{
               labels: ['Jun', 'Jul', 'Aug'],
               datasets: [
                 {
                   id: 1,
                   label: '',
                   data: [5, 6, 7],
                 },
                 {
                   id: 2,
                   label: '',
                   data: [3, 2, 1],
                 },
               ],
             }}

            options={{
              scales: {
                y: {
                  beginAtZero: true,
                  ticks: {color: '#FFFFFF'}
                }, x: {
                  ticks: {color: '#FFFFFF'}
                }
              },
              backgroundColor: [
                'rgba(255, 99, 132, 0.7)',
                'rgba(255, 159, 64, 0.7)',
                'rgba(255, 205, 86, 0.7)'
              ]
            }} />
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
